markdown: rdiscount
permalink: /:title
destination: ../../../public/internship
auto: false
paginate: 10 # pagination based on number of posts
url: http://localhost:3001/internship
exclude:
  - Rakefile
  - Gemfile
  - .gitignore
  - watch.sh
  - style.scss
  - sass